Package search: {'_pypi_ordering': False, 'version': '0.1.20150609153225', 'name': 'arvados-python-client', 'summary': 'Arvados client library'}
Fetching package metadata: ....
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Creating standard recipe for arvados-python-client-0.1.20150609153225
Converting recipe in /home/ubuntu/pypi-conda-builds/arvados-python-client
package = arvados-python-client
   dependencies = [u'ciso8601', u'google-api-python-client', u'httplib2', u'pycurl >=7.19.5.1', u'python-gflags', u'requests >=2.4', u'urllib3', u'ws4py']
Creating standard recipe for ciso8601
Converting recipe in /home/ubuntu/pypi-conda-builds/ciso8601
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-pipbuild", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 75, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 346, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 361, in execute
    build_package(package, version)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 315, in build_package
    build_package(depend)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 303, in build_package
    dependencies = convert_recipe(directory, package)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 198, in convert_recipe
    d['homeurl'] = meta['about']['home']
KeyError: 'home'
