Warning, the following versions were found for django-allauth
0.20.0
0.19.1
0.19.0
0.18.0
0.17.0
0.16.1
0.16.0
0.15.0
0.14.2
0.14.1
0.14.0
0.13.0
0.12.0
0.11.1
0.11.0
0.10.1
0.10.0
0.9.0
0.8.3
0.8.2
0.8.1
0.8.0
0.7.0
0.6.0
0.5.0
0.4.0
0.3.0
0.2.0
0.1.0
Using 0.20.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/d/django-allauth/django-allauth-0.20.0.tar.gz (289 KB) for django-allauth.
Downloading django-allauth (use --no-download to skip this step)
Using cached download
Unpacking django-allauth...
done
working in /tmp/tmpZnQka1conda_skeleton_django-allauth-0.20.0.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

Applying patch: '/tmp/tmpZnQka1conda_skeleton_django-allauth-0.20.0.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpZnQka1conda_skeleton_django-allauth-0.20.0.tar.gz/django-allauth-0.20.0
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install
