Warning, the following versions were found for django-social-auth
0.7.28
0.7.27
0.7.26
0.7.25
0.7.24
0.7.23
0.7.22
0.7.21
0.7.20
0.7.19
0.7.18
0.7.17
0.7.16
0.7.14
0.7.13
0.7.12
0.7.10
0.7.9
0.7.8
0.7.7
0.7.6
0.7.5
0.7.4
0.7.2
0.7.1
0.7.0
0.6.9
0.6.8
0.6.7
0.6.6
0.6.5
0.6.4
0.6.3
0.6.2
0.6.1
0.6.0
0.5.13
0.5.12
0.5.11
0.5.10
0.5.9
0.5.8
0.5.7
0.5.6
0.5.5
0.5.4
0.4.2
0.4.1
0.4.0
0.3.20
0.3.19
0.3.18
0.3.17
0.3.16
0.3.15
0.3.14
0.3.13
0.3.12
0.3.11
0.3.10
0.3.9
0.3.8
0.3.7
0.3.6
0.3.5
0.3.4
0.3.3
0.3.1
0.3.0
0.2.8
0.2.7
0.2.6
0.2.5
0.2.4
0.2.3
0.2.2
0.2.1
0.2.0
0.1.7
0.1.6
0.1.5
0.1.4
0.1.3
0.1.2
0.1.1
0.1.0
Using 0.7.28
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/d/django-social-auth/django-social-auth-0.7.28.tar.gz (81 KB) for django-social-auth.
Downloading django-social-auth (use --no-download to skip this step)
Using cached download
Unpacking django-social-auth...
done
working in /tmp/tmpuaiZblconda_skeleton_django-social-auth-0.7.28.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup
ImportError: No module named setuptools

The following NEW packages will be INSTALLED:

    numpy:  1.9.2-py27_0
    pyyaml: 3.11-py27_0 

Linking packages ...
[                    ]|                                                  |   0%[numpy               ]|                                                  |   0%[pyyaml              ]|#########################                         |  50%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmpuaiZblconda_skeleton_django-social-auth-0.7.28.tar.gz/pypi-distutils.patch'
$PYTHONPATH = /tmp/tmpuaiZblconda_skeleton_django-social-auth-0.7.28.tar.gz/django-social-auth-0.7.28
Error: command failed: /home/ubuntu/miniconda/envs/_build/bin/python setup.py install
