Using url https://pypi.python.org/packages/source/o/oauthlib/oauthlib-0.7.2.tar.gz (104 KB) for oauthlib.
Downloading oauthlib (use --no-download to skip this step)
Unpacking oauthlib...
done
working in /tmp/tmp8MnzvYconda_skeleton_oauthlib-0.7.2.tar.gz
Fetching package metadata: ........
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

The following NEW packages will be INSTALLED:

    numpy:      1.9.2-py27_0
    openssl:    1.0.1k-1    
    pip:        6.1.1-py27_0
    python:     2.7.9-3     
    pyyaml:     3.11-py27_0 
    readline:   6.2-2       
    setuptools: 16.0-py27_0 
    sqlite:     3.8.4.1-1   
    system:     5.8-2       
    tk:         8.5.18-0    
    yaml:       0.1.4-0     
    zlib:       1.2.8-0     

Linking packages ...
[                    ]|                                                  |   0%[openssl             ]|                                                  |   0%[readline            ]|####                                              |   8%[sqlite              ]|########                                          |  16%[system              ]|############                                      |  25%[tk                  ]|################                                  |  33%[yaml                ]|####################                              |  41%[zlib                ]|#########################                         |  50%[numpy               ]|#############################                     |  58%[python              ]|#################################                 |  66%[pyyaml              ]|#####################################             |  75%[setuptools          ]|#########################################         |  83%[pip                 ]|#############################################     |  91%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmp8MnzvYconda_skeleton_oauthlib-0.7.2.tar.gz/pypi-distutils.patch'
pyjwt not found, trying PyJWT
4
Warning, the following versions were found for PyJWT
1.1.0
1.0.1
1.0.0
0.4.3
0.4.2
0.4.1
Using 1.1.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/P/PyJWT/PyJWT-1.1.0.tar.gz (39 KB) for PyJWT.
Downloading PyJWT (use --no-download to skip this step)
PyJWT-1.1.0.ta   0% |                              | ETA:  --:--:--   0.00  B/sPyJWT-1.1.0.ta  40% |############                   | ETA:  0:00:00   4.00 MB/sPyJWT-1.1.0.ta  81% |#########################      | ETA:  0:00:00 731.80 kB/sPyJWT-1.1.0.ta 100% |###############################| ETA:  0:00:00 884.33 kB/sPyJWT-1.1.0.ta 100% |###############################| Time: 0:00:00 874.02 kB/s
Unpacking PyJWT...
done
working in /tmp/tmps6hFD9conda_skeleton_PyJWT-1.1.0.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

Applying patch: '/tmp/tmps6hFD9conda_skeleton_PyJWT-1.1.0.tar.gz/pypi-distutils.patch'
Using url https://pypi.python.org/packages/source/b/blinker/blinker-1.3.tar.gz (89 KB) for blinker.
Downloading blinker (use --no-download to skip this step)
blinker-1.3.ta   0% |                              | ETA:  --:--:--   0.00  B/sblinker-1.3.ta  17% |#####                          | Time: 0:00:00 243.98 kB/sblinker-1.3.ta  35% |###########                    | Time: 0:00:00 337.02 kB/sblinker-1.3.ta  53% |################               | Time: 0:00:00 471.82 kB/sblinker-1.3.ta  71% |######################         | Time: 0:00:00 435.35 kB/sblinker-1.3.ta  89% |###########################    | Time: 0:00:00 532.03 kB/sblinker-1.3.ta 100% |###############################| Time: 0:00:00 592.18 kB/sblinker-1.3.ta 100% |###############################| Time: 0:00:00 590.93 kB/sblinker-1.3.ta 100% |###############################| Time: 0:00:00 589.52 kB/s
Unpacking blinker...
done
working in /tmp/tmp9kX4IQconda_skeleton_blinker-1.3.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

Applying patch: '/tmp/tmp9kX4IQconda_skeleton_blinker-1.3.tar.gz/pypi-distutils.patch'
pyjwt not found, trying PyJWT
2
Warning, the following versions were found for PyJWT
1.1.0
1.0.1
1.0.0
0.4.3
0.4.2
0.4.1
Using 1.1.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/P/PyJWT/PyJWT-1.1.0.tar.gz (39 KB) for PyJWT.
Downloading PyJWT (use --no-download to skip this step)
Using cached download
Unpacking PyJWT...
done
working in /tmp/tmpp7LtBQconda_skeleton_PyJWT-1.1.0.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

Applying patch: '/tmp/tmpp7LtBQconda_skeleton_PyJWT-1.1.0.tar.gz/pypi-distutils.patch'
Using url https://pypi.python.org/packages/source/u/unittest2/unittest2-1.0.1.tar.gz (79 KB) for unittest2.
Downloading unittest2 (use --no-download to skip this step)
Using cached download
Unpacking unittest2...
done
working in /tmp/tmpNBMXyVconda_skeleton_unittest2-1.0.1.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.



Applying patch: '/tmp/tmpNBMXyVconda_skeleton_unittest2-1.0.1.tar.gz/pypi-distutils.patch'
Traceback (most recent call last):
  File "/home/hargup/anaconda/bin/conda-skeleton", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/hargup/210fs/conda-build/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/hargup/210fs/conda-build/conda_build/main_skeleton.py", line 201, in main
    args_func(args, p)
  File "/home/hargup/210fs/conda-build/conda_build/main_build.py", line 329, in args_func
    args.func(args, p)
  File "/home/hargup/210fs/conda-build/conda_build/main_skeleton.py", line 215, in execute
    pypi.main(args, parser)
  File "/home/hargup/210fs/conda-build/conda_build/pypi.py", line 388, in main
    get_package_metadata(args, package, d, data)
  File "/home/hargup/210fs/conda-build/conda_build/pypi.py", line 446, in get_package_metadata
    pkginfo = yaml.load(fn)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/hargup/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/home/hargup/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 93, in construct_object
    data = generator.next()
  File "/home/hargup/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 568, in construct_python_object
    instance = self.make_python_instance(suffix, node, newobj=True)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 540, in make_python_instance
    cls = self.find_python_name(suffix, node.start_mark)
  File "/home/hargup/anaconda/lib/python2.7/site-packages/yaml/constructor.py", line 513, in find_python_name
    module.__name__), mark)
yaml.constructor.ConstructorError: while constructing a Python object
cannot find 'late_version' in the module '__main__'
  in "/tmp/tmpNBMXyVconda_skeleton_unittest2-1.0.1.tar.gz/pkginfo.yaml", line 19, column 10
