Warning, the following versions were found for pkginfo
1.2.1
1.2
1.2b1
1.1
1.1b1
1.0
1.0b2
1.0b1
0.9.1
0.9
0.8
0.7
0.6
0.5
0.4.1
0.4
0.3
0.2
0.1.1
0.1
Using 1.2.1
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/p/pkginfo/pkginfo-1.2.1.tar.gz (30 KB) for pkginfo.
Downloading pkginfo (use --no-download to skip this step)
Using cached download
Unpacking pkginfo...
done
working in /tmp/tmpAzQuvQconda_skeleton_pkginfo-1.2.1.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.



Applying patch: '/tmp/tmpAzQuvQconda_skeleton_pkginfo-1.2.1.tar.gz/pypi-distutils.patch'
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-skeleton", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_skeleton.py", line 244, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 346, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_skeleton.py", line 258, in execute
    pypi.main(args, parser)
  File "/home/ubuntu/conda-build/conda_build/pypi.py", line 390, in main
    get_package_metadata(args, package, d, data)
  File "/home/ubuntu/conda-build/conda_build/pypi.py", line 538, in get_package_metadata
    d['entry_points'] = INDENT.join([''] + entry_list)
TypeError: sequence item 1: expected string, list found
