Package search: {'_pypi_ordering': False, 'version': '2.6.0', 'name': 'python-neutronclient', 'summary': 'CLI and Client Library for OpenStack Networking'}
Fetching package metadata: ....
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Creating standard recipe for python-neutronclient-2.6.0
Converting recipe in /home/ubuntu/pypi-conda-builds/python-neutronclient
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-pipbuild", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 75, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 346, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 361, in execute
    build_package(package, version)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 303, in build_package
    dependencies = convert_recipe(directory, package)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 198, in convert_recipe
    d['homeurl'] = meta['about']['home']
KeyError: 'home'
