An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Package search: {'_pypi_ordering': False, 'version': '2015.5.1', 'name': 'salt', 'summary': 'Portable, distributed, remote execution and configuration management system'}
Creating standard recipe for salt-2015.5.1
Converting recipe in /home/ubuntu/pypi-conda-builds/salt
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-pipbuild", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 80, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 346, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 360, in execute
    build_package(package, version, noarch_python=args.noarch_python)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 301, in build_package
    noarch_python=noarch_python)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 183, in convert_recipe
    d['homeurl'] = meta['about']['home']
KeyError: 'home'
