Warning, the following versions were found for supervisor
3.1.3
3.1.2
3.1.1
3.1.0
3.0
3.0b2
3.0b1
3.0a12
3.0a11
3.0a10
3.0a9
3.0a8
3.0a7
3.0a6
3.0a5
3.0a4
3.0a3
3.0a2
3.0a1
2.2b1
2.1
2.1b1
2.0
2.0b1
a3
Using 3.1.3
Use --version to specify a different version.
Using url https://pypi.python.org/packages/source/s/supervisor/supervisor-3.1.3.tar.gz (382 KB) for supervisor.
Downloading supervisor (use --no-download to skip this step)
Using cached download
Unpacking supervisor...
done
working in /tmp/tmpTCgsZ7conda_skeleton_supervisor-3.1.3.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.



The following NEW packages will be INSTALLED:

    numpy:  1.9.2-py27_0
    pyyaml: 3.11-py27_0 
    yaml:   0.1.4-0     

Linking packages ...
[                    ]|                                                  |   0%[yaml                ]|                                                  |   0%[numpy               ]|################                                  |  33%[pyyaml              ]|#################################                 |  66%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmpTCgsZ7conda_skeleton_supervisor-3.1.3.tar.gz/pypi-distutils.patch'
celementtree not found, trying cElementTree
0
Warning, the following versions were found for cElementTree
1.0.2-20050302
1.0.1-20050130
Using 1.0.2-20050302
Use --version to specify a different version.
Using url http://effbot.org/downloads#celementtree (0 B) for cElementTree.
Downloading cElementTree (use --no-download to skip this step)
Unpacking cElementTree...
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-skeleton", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_skeleton.py", line 244, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 346, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_skeleton.py", line 258, in execute
    pypi.main(args, parser)
  File "/home/ubuntu/conda-build/conda_build/pypi.py", line 388, in main
    get_package_metadata(args, package, d, data)
  File "/home/ubuntu/conda-build/conda_build/pypi.py", line 475, in get_package_metadata
    unpack(join(SRC_CACHE, d['filename']), tempdir)
  File "/home/ubuntu/conda-build/conda_build/pypi.py", line 692, in unpack
    raise Exception("not a valid source")
Exception: not a valid source
