Package search: {'_pypi_ordering': False, 'version': '1.0.1', 'name': 'unittest2', 'summary': 'The new features in unittest backported to Python 2.4+.'}
Fetching package metadata: ....
Error: prefix already exists: /home/ubuntu/miniconda/envs/_pipbuild_
You are using pip version 7.0.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting unittest2==1.0.1
  Downloading http://localhost/packages/3.4/u/unittest2/unittest2-1.0.1-py2.py3-none-any.whl (95kB)
Collecting argparse (from unittest2==1.0.1)
  Downloading http://localhost/packages/2.7/a/argparse/argparse-1.3.0-py2.py3-none-any.whl
Collecting traceback2 (from unittest2==1.0.1)
  Downloading http://localhost/packages/3.4/t/traceback2/traceback2-1.4.0-py2.py3-none-any.whl
Collecting six>=1.4 (from unittest2==1.0.1)
  Downloading http://localhost/packages/3.3/s/six/six-1.9.0-py2.py3-none-any.whl
Collecting linecache2 (from traceback2->unittest2==1.0.1)
  Downloading http://localhost/packages/3.5/l/linecache2/linecache2-1.0.0-py2.py3-none-any.whl
Installing collected packages: argparse, linecache2, traceback2, six, unittest2
Successfully installed argparse-1.3.0 linecache2-1.0.0 six-1.9.0 traceback2-1.4.0 unittest2-1.0.1
Fetching package metadata: ....

Package plan for package removal in environment /home/ubuntu/miniconda/envs/_pipbuild_:

The following packages will be REMOVED:

    openssl:    1.0.1k-1    
    pip:        7.0.1-py27_0
    python:     2.7.10-0    
    readline:   6.2-2       
    setuptools: 17.0-py27_0 
    sqlite:     3.8.4.1-1   
    system:     5.8-2       
    tk:         8.5.18-0    
    zlib:       1.2.8-0     

Unlinking packages ...
[                    ]|                                                  |   0%[openssl             ]|                                                  |   0%[pip                 ]|#####                                             |  11%[python              ]|###########                                       |  22%[readline            ]|################                                  |  33%[setuptools          ]|######################                            |  44%[sqlite              ]|###########################                       |  55%[system              ]|#################################                 |  66%[tk                  ]|######################################            |  77%[zlib                ]|############################################      |  88%[      COMPLETE      ]|##################################################| 100%
Creating standard recipe for unittest2-1.0.1
Using url https://pypi.python.org/packages/source/u/unittest2/unittest2-1.0.1.tar.gz (79 KB) for unittest2.
Downloading unittest2 (use --no-download to skip this step)
Using cached download
Unpacking unittest2...
done
working in /tmp/tmpRsZve6conda_skeleton_unittest2-1.0.1.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.



The following NEW packages will be INSTALLED:

    numpy:  1.9.2-py27_0
    pyyaml: 3.11-py27_0 
    yaml:   0.1.4-0     

Linking packages ...
[                    ]|                                                  |   0%[yaml                ]|                                                  |   0%[numpy               ]|################                                  |  33%[pyyaml              ]|#################################                 |  66%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmpRsZve6conda_skeleton_unittest2-1.0.1.tar.gz/pypi-distutils.patch'
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-skeleton", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_skeleton.py", line 231, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 346, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_skeleton.py", line 245, in execute
    pypi.main(args, parser)
  File "/home/ubuntu/conda-build/conda_build/pypi.py", line 388, in main
    get_package_metadata(args, package, d, data)
  File "/home/ubuntu/conda-build/conda_build/pypi.py", line 452, in get_package_metadata
    pkginfo = yaml.load(fn)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 93, in construct_object
    data = generator.next()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 568, in construct_python_object
    instance = self.make_python_instance(suffix, node, newobj=True)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 540, in make_python_instance
    cls = self.find_python_name(suffix, node.start_mark)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 513, in find_python_name
    module.__name__), mark)
yaml.constructor.ConstructorError: while constructing a Python object
cannot find 'late_version' in the module '__main__'
  in "/tmp/tmpRsZve6conda_skeleton_unittest2-1.0.1.tar.gz/pkginfo.yaml", line 20, column 10

conda create -n _pipbuild_ --yes python pip
/home/ubuntu/miniconda/envs/_pipbuild_/bin/pip install unittest2==1.0.1
Getting dependencies...
package = unittRemoving old build directory
Removing old work directory
BUILD START: argparse-1.3.0-py27_0
Fetching package metadata: ......
Solving package specifications: .+ pip install argparse
You are using pip version 7.0.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting argparse
  Downloading http://localhost/packages/2.7/a/argparse/argparse-1.3.0-py2.py3-none-any.whl
Installing collected packages: argparse
Successfully installed argparse-1.3.0

The following NEW packages will be INSTALLED:

    openssl:    1.0.1k-1    
    pip:        7.0.1-py27_0
    python:     2.7.10-0    
    readline:   6.2-2       
    setuptools: 17.0-py27_0 
    sqlite:     3.8.4.1-1   
    system:     5.8-2       
    tk:         8.5.18-0    
    zlib:       1.2.8-0     

Linking packages ...
[                    ]|                                                  |   0%[openssl             ]|                                                  |   0%[readline            ]|#####                                             |  11%[sqlite              ]|###########                                       |  22%[system              ]|################                                  |  33%[tk                  ]|######################                            |  44%[zlib                ]|###########################                       |  55%[python              ]|#################################                 |  66%[setuptools          ]|######################################            |  77%[pip                 ]|############################################      |  88%[      COMPLETE      ]|##################################################| 100%
Removing old work directory
Copying /home/ubuntu/pypi-conda-builds/argparse to /home/ubuntu/miniconda/conda-bld/work
Package: argparse-1.3.0-py27_0
source tree in: /home/ubuntu/miniconda/conda-bld/work
number of files: 8
Fixing permissions
Fixing permissions
BUILD END: argparse-1.3.0-py27_0
# If you want to upload this package to binstar.org later, type:
#
# $ binstar upload /home/ubuntu/miniconda/conda-bld/linux-64/argparse-1.3.0-py27_0.tar.bz2
#
# To have conda build upload to binstar automatically, use
# $ conda config --set binstar_upload yes

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


est2
   dependencies = ['argparse', 'traceback2', 'six']
Creating standard recipe for argparse
Converting recipe in /home/ubuntu/pypi-conda-builds/argparse
package = argparse
   dependencies = []
Building conda package for argparse
Creating standard recipe for traceback2
Converting recipe in /home/ubuntu/pypi-conda-builds/traceback2
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-pipbuild", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 75, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 346, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 361, in execute
    build_package(package, version)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 315, in build_package
    build_package(depend)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 303, in build_package
    dependencies = convert_recipe(directory, package)
  File "/home/ubuntu/conda-build/conda_build/main_pipbuild.py", line 198, in convert_recipe
    d['homeurl'] = meta['about']['home']
KeyError: 'home'
