Using url https://pypi.python.org/packages/source/u/unittest-xml-reporting/unittest-xml-reporting-1.12.0.tar.gz (13 KB) for unittest-xml-reporting.
Downloading unittest-xml-reporting (use --no-download to skip this step)
Using cached download
Unpacking unittest-xml-reporting...
done
working in /tmp/tmpcPxxHBconda_skeleton_unittest-xml-reporting-1.12.0.tar.gz
Fetching package metadata: ......
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).

The following NEW packages will be INSTALLED:

    numpy:      1.9.2-py27_0
    openssl:    1.0.1k-1    
    pip:        6.1.1-py27_0
    python:     2.7.9-3     
    pyyaml:     3.11-py27_0 
    readline:   6.2-2       
    setuptools: 16.0-py27_0 
    sqlite:     3.8.4.1-1   
    system:     5.8-2       
    tk:         8.5.18-0    
    yaml:       0.1.4-0     
    zlib:       1.2.8-0     

Linking packages ...
[                    ]|                                                  |   0%[openssl             ]|                                                  |   0%[readline            ]|####                                              |   8%[sqlite              ]|########                                          |  16%[system              ]|############                                      |  25%[tk                  ]|################                                  |  33%[yaml                ]|####################                              |  41%[zlib                ]|#########################                         |  50%[numpy               ]|#############################                     |  58%[python              ]|#################################                 |  66%[pyyaml              ]|#####################################             |  75%[setuptools          ]|#########################################         |  83%[pip                 ]|#############################################     |  91%[      COMPLETE      ]|##################################################| 100%
Applying patch: '/tmp/tmpcPxxHBconda_skeleton_unittest-xml-reporting-1.12.0.tar.gz/pypi-distutils.patch'
Using url https://pypi.python.org/packages/source/u/unittest2/unittest2-1.0.1.tar.gz (79 KB) for unittest2.
Downloading unittest2 (use --no-download to skip this step)
Using cached download
Unpacking unittest2...
done
working in /tmp/tmp1CAXYUconda_skeleton_unittest2-1.0.1.tar.gz
Solving package specifications: .patching file core.py
Hunk #1 succeeded at 168 with fuzz 2 (offset 2 lines).
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.



Applying patch: '/tmp/tmp1CAXYUconda_skeleton_unittest2-1.0.1.tar.gz/pypi-distutils.patch'
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-skeleton", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ubuntu/conda-build/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/conda-build/conda_build/main_skeleton.py", line 201, in main
    args_func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_build.py", line 329, in args_func
    args.func(args, p)
  File "/home/ubuntu/conda-build/conda_build/main_skeleton.py", line 215, in execute
    pypi.main(args, parser)
  File "/home/ubuntu/conda-build/conda_build/pypi.py", line 389, in main
    get_package_metadata(args, package, d, data)
  File "/home/ubuntu/conda-build/conda_build/pypi.py", line 447, in get_package_metadata
    pkginfo = yaml.load(fn)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 48, in construct_document
    for dummy in generator:
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 208, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 133, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 93, in construct_object
    data = generator.next()
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 568, in construct_python_object
    instance = self.make_python_instance(suffix, node, newobj=True)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 540, in make_python_instance
    cls = self.find_python_name(suffix, node.start_mark)
  File "/home/ubuntu/miniconda/lib/python2.7/site-packages/yaml/constructor.py", line 513, in find_python_name
    module.__name__), mark)
yaml.constructor.ConstructorError: while constructing a Python object
cannot find 'late_version' in the module '__main__'
  in "/tmp/tmp1CAXYUconda_skeleton_unittest2-1.0.1.tar.gz/pkginfo.yaml", line 20, column 10
